server:
  port: 8086

spring:
  application:
    name: finflow-analytics-service
  config:
    import: optional:configserver:http://localhost:8889
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: FinFlow Analytics Service
    version: 1.0.0